### ISSUE TITLE
Visual Studio Code Doesn't Display Type Warnings

### ISSUE THREAD

**Issue by jeremyjh** [geakstr/svelte-3-rollup-typescript-vscode#1]
I've cloned this repo, opened `Counter.svelete`, and changed it so there is a typeerror:

![image](https://user-images.githubusercontent.com/90510/59982420-18a21880-95e0-11e9-960d-8f50f52884d1.png)

However, no error is displayed in the Visual Studio Code problem window. This seems similar to the report in https://github.com/UnwrittenFun/svelte-vscode/issues/43. Changing lang to other suggested values doesn't help.

**Comment by geakstr** [comment]
Hi @jeremyjh! Yes, as you mentioned, this is the svelte-vscode extension issue. The only thing my repo does for vs code/svelte-vscode extension is `svelte.config.js` file which adds support (mostly suppress parse type annotations errors) for `<script>` block which contains typescript code. Without this file svelte-vscode won't provide even basic support for ts code inside .svelte files (you can try to rename `svelte.config.js` file somehow, restart vs code and see what happens). `svelte.config.js` is undocumented svelte-vscode thing (I found information about it bit by bit). I'll do all my best and will submit docs related pull request about it to their repo.
